package org.westford.launch.indirect

object NativeConstants {

    val OPCODE_WESTMALLE_LAUNCHER_OPEN = 0

    val EVENT_WESTMALLE_LAUNCHER_SUCCESS = 0
    val EVENT_WESTMALLE_LAUNCHER_ACTIVATE = 1
    val EVENT_WESTMALLE_LAUNCHER_DEACTIVATE = 2

    val ENV_WESTFORD_TTY_FD = "WESTFORD_TTY_FD"
    val ENV_WESTFORD_LAUNCHER_SOCK = "WESTFORD_LAUNCHER_SOCK"

}
